FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/{{ .AppName }} ./cmd/{{ .Context }}

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /bin/{{ .AppName }} /bin/{{ .AppName }}
ENTRYPOINT ["/bin/{{ .AppName }}"]
